# Generated by Django 2.1.3 on 2018-12-08 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Date')),
                ('action_type', models.IntegerField(choices=[(0, 'Created'), (1, 'Modified')], verbose_name='Type of action')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object link')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_content', to='contenttypes.ContentType', verbose_name='Related object')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Performer')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name_plural': 'Actions',
                'verbose_name': 'Action',
            },
        ),
    ]
