# Generated by Django 2.0.7 on 2018-11-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20181108_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('ADD', 'Add child record'), ('MODIFY', 'Modify or edit record'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('RENEW', 'Renew'), ('DELETE', 'Delete'), ('CHANGE PASS', 'Change Password Through OPAC'), ('RESERVE', 'Reserve'), ('FINE', 'Collect fine'), ('WRITEOFF', 'Write off fine'), ('RUN', 'Run report'), ('RENEWSELF', 'Renew self'), ('RESERVESELF', 'Reserve self')], max_length=11),
        ),
    ]
