# Generated by Django 2.0.7 on 2018-11-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_auto_20181111_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.Items'),
        ),
    ]
