# Generated by Django 2.0.7 on 2018-11-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_auto_20181112_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexitlogs',
            name='timeofexit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
