# Generated by Django 2.0.7 on 2018-11-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_auto_20181112_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopwords',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
