# Generated by Django 2.0.7 on 2018-11-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_auto_20181113_0409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suggestion',
            unique_together={('title', 'suggestedby')},
        ),
    ]
