# Generated by Django 2.0.7 on 2018-11-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_auto_20181113_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.FileField(upload_to='images/patronimages')),
            ],
            options={
                'ordering': ['patron__cardnumber'],
            },
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='debarred',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronphotos',
            name='patron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intranet.Borrowers'),
        ),
    ]
