# Generated by Django 2.0.7 on 2018-11-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_auto_20181114_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
