# Generated by Django 2.1.3 on 2018-12-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryexitlogs',
            options={'ordering': ('-timeofentry', 'cardnumber')},
        ),
        migrations.AlterModelOptions(
            name='quotations',
            options={'ordering': ('source', 'text')},
        ),
        migrations.AlterField(
            model_name='entryexitlogs',
            name='cardnumber',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='entryexitlogs',
            name='timeofentry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='entryexitlogs',
            unique_together={('cardnumber', 'timeofentry')},
        ),
        migrations.AlterUniqueTogether(
            name='quotations',
            unique_together={('source', 'text')},
        ),
    ]
