# Generated by Django 2.1.3 on 2018-12-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20181210_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexitlogs',
            name='timespent',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
