# Generated by Django 2.1.3 on 2018-12-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_entryexitlogs_timespent'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexitlogs',
            name='imageurl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
