# Generated by Django 2.1.3 on 2018-12-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_entryexitlogs_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='accountlines',
            name='itemnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.Items'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.Items'),
        ),
    ]
