# Generated by Django 2.0.7 on 2018-11-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_auto_20181112_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='cancellationdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='notificationdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='waitingdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
