# Generated by Django 2.0.7 on 2018-11-13 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_auto_20181113_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestionid', models.AutoField(primary_key=True, serialize=False)),
                ('suggesteddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('acceptedby', models.IntegerField(blank=True, null=True)),
                ('accepteddate', models.DateTimeField(blank=True, null=True)),
                ('rejectedby', models.IntegerField(blank=True, null=True)),
                ('rejecteddate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASKED', 'User asked'), ('ACCEPTED', 'Suggestion has been accepted'), ('REJECTED', 'Suggestion has been rejected')], default='ASKED', max_length=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('copyrightdate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publishercode', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ('firstname', 'lastname')},
        ),
        migrations.AlterModelOptions(
            name='biblio',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='corporateauthor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='moderatorreasons',
            options={'ordering': ('reason',)},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='accountlines',
            name='accounttype',
            field=models.CharField(choices=[('F', 'Fine levied'), ('FU', 'Overdue Fine'), ('N', 'New Card'), ('FOR', 'Forgiven'), ('FFOR', 'Forgiven Overdue Fine'), ('M', 'Sundry'), ('PAY', 'Payment'), ('REP', 'Replacement Charge'), ('RES', 'Reserve Charge'), ('W', 'Written off'), ('RENT', 'Rental Charge')], max_length=4),
        ),
        migrations.AlterField(
            model_name='biblio',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.Language'),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemstatus',
            field=models.CharField(choices=[('AV', 'Available'), ('OL', 'On Loan'), ('DM', 'Damaged'), ('LO', 'Lost'), ('LP', 'Lost and Paid for'), ('MI', 'Missing'), ('WD', 'Withdrawn'), ('BD', 'In Bindery')], default='AV', max_length=2),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='status',
            field=models.CharField(choices=[('ASKED', 'User asked'), ('ACCEPTED', 'Suggestion has been accepted'), ('REJECTED', 'Suggestion has been rejected')], default='ASKED', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('comment', 'biblionumber')},
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('tag', 'biblionumber')},
        ),
        migrations.AddField(
            model_name='suggestion',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.ModeratorReasons'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Borrowers'),
        ),
    ]
